import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:printing/printing.dart';
import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../../core/widgets/app_text_field.dart';
import '../../../../core/network/api_exception.dart';
import '../../data/clinic_repository.dart';
import '../../domain/clinic_models.dart';
import '../../../../l10n/app_localizations.dart';

/// Ch. 6 "Create Prescription / Ordonnance". Two modes in one screen,
/// same pattern the rest of this module already uses for
/// create-vs-view (e.g. clinic_patient_profile_screen reusing one
/// screen for both): [viewOnlyPrescriptionId] null → creation form for
/// [patientId]; non-null → read-only view of that existing prescription
/// (fetched fresh via GET /clinic/prescriptions/:id, not the summary
/// already in the patient profile list, so it always shows the current
/// saved state).
///
/// Printing (Ch. 7, remaining-issues pass) now goes through the
/// `printing` package's OS print/share sheet, fed by the backend's
/// pdfkit-generated bytes (GET /clinic/prescriptions/:id/pdf) — no PDF
/// is ever built on-device, so the printed layout always matches
/// exactly what pdf.service.js renders server-side.
class ClinicPrescriptionFormScreen extends ConsumerStatefulWidget {
  const ClinicPrescriptionFormScreen({
    super.key,
    required this.patientId,
    this.viewOnlyPrescriptionId,
  });

  final String patientId;
  final String? viewOnlyPrescriptionId;

  @override
  ConsumerState<ClinicPrescriptionFormScreen> createState() => _ClinicPrescriptionFormScreenState();
}

class _MedicationRow {
  _MedicationRow()
      : nameController = TextEditingController(),
        dosageController = TextEditingController(),
        quantityController = TextEditingController(),
        frequencyController = TextEditingController(),
        durationController = TextEditingController(),
        instructionsController = TextEditingController();

  final TextEditingController nameController;
  final TextEditingController dosageController;
  final TextEditingController quantityController;
  final TextEditingController frequencyController;
  final TextEditingController durationController;
  final TextEditingController instructionsController;

  void dispose() {
    nameController.dispose();
    dosageController.dispose();
    quantityController.dispose();
    frequencyController.dispose();
    durationController.dispose();
    instructionsController.dispose();
  }
}

class _ClinicPrescriptionFormScreenState extends ConsumerState<ClinicPrescriptionFormScreen> {
  final List<_MedicationRow> _rows = [_MedicationRow()];
  final _notesController = TextEditingController();
  bool _saving = false;

  ClinicPrescription? _viewedPrescription;
  bool _loadingView = false;
  String? _loadError;

  bool get _isViewMode => widget.viewOnlyPrescriptionId != null;

  @override
  void initState() {
    super.initState();
    if (_isViewMode) {
      _loadPrescription();
    }
  }

  Future<void> _loadPrescription() async {
    setState(() => _loadingView = true);
    try {
      final prescription =
          await ref.read(clinicRepositoryProvider).getPrescription(widget.viewOnlyPrescriptionId!);
      if (mounted) setState(() => _viewedPrescription = prescription);
    } on ApiException catch (e) {
      if (mounted) setState(() => _loadError = e.message);
    } catch (_) {
      if (mounted) setState(() => _loadError = AppLocalizations.of(context)!.networkError);
    } finally {
      if (mounted) setState(() => _loadingView = false);
    }
  }

  @override
  void dispose() {
    for (final row in _rows) {
      row.dispose();
    }
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _save() async {
    final l10n = AppLocalizations.of(context)!;
    final items = _rows
        .where((r) => r.nameController.text.trim().isNotEmpty)
        .map((r) => ClinicPrescriptionItem(
              medicationName: r.nameController.text.trim(),
              dosage: r.dosageController.text.trim(),
              quantity: r.quantityController.text.trim(),
              frequency: r.frequencyController.text.trim(),
              duration: r.durationController.text.trim(),
              instructions: r.instructionsController.text.trim(),
            ))
        .toList();

    if (items.isEmpty) {
      ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l10n.medicationRequiredMessage)));
      return;
    }

    setState(() => _saving = true);
    try {
      await ref.read(clinicRepositoryProvider).createPrescription(
            patientId: widget.patientId,
            items: items,
            notes: _notesController.text.trim().isEmpty ? null : _notesController.text.trim(),
          );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l10n.prescriptionSavedMessage)));
        Navigator.of(context).pop(true);
      }
    } on ApiException catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(e.message)));
    } catch (_) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(l10n.networkError)));
    } finally {
      if (mounted) setState(() => _saving = false);
    }
  }

  String _formatDate(DateTime date) =>
      '${date.year}-${date.month.toString().padLeft(2, '0')}-${date.day.toString().padLeft(2, '0')}';

  @override
  Widget build(BuildContext context) {
    final l10n = AppLocalizations.of(context)!;

    if (_isViewMode) {
      return Scaffold(
        appBar: AppBar(
          title: Text(l10n.prescriptionsTitle),
          actions: [
            if (_viewedPrescription != null)
              IconButton(
                icon: const Icon(Icons.print_outlined),
                onPressed: () => Printing.layoutPdf(
                  onLayout: (_) => ref
                      .read(clinicRepositoryProvider)
                      .fetchPrescriptionPdf(widget.viewOnlyPrescriptionId!),
                  name: _viewedPrescription!.prescriptionNumber,
                ),
              ),
          ],
        ),
        body: _loadingView
            ? const Center(child: CircularProgressIndicator())
            : _loadError != null
                ? Center(child: Text(_loadError!))
                : _viewedPrescription == null
                    ? const SizedBox.shrink()
                    : ListView(
                        padding: const EdgeInsets.all(AppSpacing.sm),
                        children: [
                          Text(
                            '${l10n.prescriptionNumberLabel}: ${_viewedPrescription!.prescriptionNumber}',
                            style: Theme.of(context).textTheme.titleLarge,
                          ),
                          Text(_formatDate(_viewedPrescription!.issuedAt)),
                          if (_viewedPrescription!.doctorName != null)
                            Text(_viewedPrescription!.doctorName!),
                          const SizedBox(height: AppSpacing.md),
                          ..._viewedPrescription!.items.map(
                            (item) => Container(
                              margin: const EdgeInsets.only(bottom: AppSpacing.xs),
                              padding: const EdgeInsets.all(AppSpacing.sm),
                              decoration: BoxDecoration(
                                color: Theme.of(context).colorScheme.surface,
                                borderRadius: BorderRadius.circular(AppSpacing.radiusCard),
                                boxShadow: AppSpacing.cardElevation,
                              ),
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(item.medicationName, style: Theme.of(context).textTheme.titleSmall),
                                  Text(
                                    [
                                      if (item.dosage != null && item.dosage!.isNotEmpty) item.dosage!,
                                      if (item.frequency != null && item.frequency!.isNotEmpty)
                                        item.frequency!,
                                      if (item.duration != null && item.duration!.isNotEmpty)
                                        item.duration!,
                                    ].join(' · '),
                                  ),
                                  if (item.instructions != null && item.instructions!.isNotEmpty)
                                    Text(item.instructions!),
                                ],
                              ),
                            ),
                          ),
                          if (_viewedPrescription!.notes != null) ...[
                            const SizedBox(height: AppSpacing.sm),
                            Text(l10n.notesLabel, style: Theme.of(context).textTheme.titleSmall),
                            Text(_viewedPrescription!.notes!),
                          ],
                        ],
                      ),
      );
    }

    return Scaffold(
      appBar: AppBar(title: Text(l10n.newPrescriptionAction)),
      body: ListView(
        padding: const EdgeInsets.all(AppSpacing.sm),
        children: [
          ..._rows.asMap().entries.map((entry) {
            final index = entry.key;
            final row = entry.value;
            return Container(
              margin: const EdgeInsets.only(bottom: AppSpacing.sm),
              padding: const EdgeInsets.all(AppSpacing.sm),
              decoration: BoxDecoration(
                color: Theme.of(context).colorScheme.surface,
                borderRadius: BorderRadius.circular(AppSpacing.radiusCard),
                boxShadow: AppSpacing.cardElevation,
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Expanded(
                        child: AppTextField(label: l10n.medicationNameLabel, controller: row.nameController),
                      ),
                      if (_rows.length > 1)
                        IconButton(
                          icon: const Icon(Icons.close, color: AppColors.danger),
                          onPressed: () => setState(() {
                            row.dispose();
                            _rows.removeAt(index);
                          }),
                        ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Row(
                    children: [
                      Expanded(
                        child: AppTextField(label: l10n.dosageLabel, controller: row.dosageController),
                      ),
                      const SizedBox(width: AppSpacing.xs),
                      Expanded(
                        child: AppTextField(label: l10n.quantityLabel, controller: row.quantityController),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Row(
                    children: [
                      Expanded(
                        child: AppTextField(label: l10n.frequencyLabel, controller: row.frequencyController),
                      ),
                      const SizedBox(width: AppSpacing.xs),
                      Expanded(
                        child: AppTextField(label: l10n.durationLabel, controller: row.durationController),
                      ),
                    ],
                  ),
                  const SizedBox(height: AppSpacing.xs),
                  AppTextField(
                    label: l10n.instructionsLabel,
                    controller: row.instructionsController,
                  ),
                ],
              ),
            );
          }),
          OutlinedButton.icon(
            onPressed: () => setState(() => _rows.add(_MedicationRow())),
            icon: const Icon(Icons.add),
            label: Text(l10n.addMedicationAction),
          ),
          const SizedBox(height: AppSpacing.sm),
          AppTextField(label: l10n.notesLabel, controller: _notesController),
          const SizedBox(height: AppSpacing.md),
          ElevatedButton(
            onPressed: _saving ? null : _save,
            child: _saving
                ? const SizedBox(
                    height: 20,
                    width: 20,
                    child: CircularProgressIndicator(strokeWidth: 2),
                  )
                : Text(l10n.savePrescriptionAction),
          ),
        ],
      ),
    );
  }
}
